set(FREEIMAGE_LIBRARY_PREFIX "lib")
set(FREEIMAGE_LIBRARY_NAME "freeimage")
set(FREEIMAGE_LIBRARY_EXTENSION "a")
if(WIN32)
  set(FREEIMAGE_LIBRARY_PREFIX "")
  set(FREEIMAGE_LIBRARY_NAME "FreeImage")
  set(FREEIMAGE_LIBRARY_EXTENSION "lib")
endif()

set(FREEIMAGE_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../deps/freeimage/include")
set(FREEIMAGE_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/../deps/freeimage/lib/${FREEIMAGE_LIBRARY_PREFIX}${FREEIMAGE_LIBRARY_NAME}.${FREEIMAGE_LIBRARY_EXTENSION}")

find_library(FREEIMAGE_LIBRARY NAMES freeimage-3.18.0 FreeImage PATHS ${CMAKE_CURRENT_LIST_DIR}/../deps/freeimage/lib)