#list(APPEND CMAKE_PREFIX_PATH "./deps/sdl/include")
#list(APPEND CMAKE_PREFIX_PATH "./deps/sdl/lib")

set(SDL2_LIBRARY_PREFIX "lib")
set(SDL2_LIBRARY_EXTENSION "a")
if(WIN32)
  set(SDL2_LIBRARY_PREFIX "")
  set(SDL2_LIBRARY_EXTENSION "lib")
endif()

set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_LIST_DIR}/../deps/sdl/include")
set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/../deps/sdl/lib/${SDL2_LIBRARY_PREFIX}SDL2.${SDL2_LIBRARY_EXTENSION};")

if(NOT SDL2_BUILDING_LIBRARY)
  set(SDL2_LIBRARIES "${SDL2_LIBRARIES};${CMAKE_CURRENT_LIST_DIR}/../deps/sdl/lib/${SDL2_LIBRARY_PREFIX}SDL2main.${SDL2_LIBRARY_EXTENSION}")
endif()


#find_file(SDL_INCLUDE_DIR NAME SDL.h HINTS SDL2)
#find_library(SDL_LIBRARY NAME SDL2)

#find_package(SDL2 2.0.8 REQUIRED)